# ──────────────────────────────────────────────────────────────────────────────
# render-pdf.R — PDF backend for fr_render()
#
# Thin wrapper: generates .tex via render_latex(), compiles with XeLaTeX.
# Uses tinytex::xelatex() when available (auto-installs missing LaTeX
# packages), falls back to raw system2() otherwise.
# ──────────────────────────────────────────────────────────────────────────────

# ── Exported helpers ─────────────────────────────────────────────────────────

#' List Required LaTeX Packages
#'
#' Returns the CTAN package names that arframe's PDF backend requires. These
#' packages are loaded in the LaTeX preamble generated by [fr_render()] when
#' producing `.pdf` or `.tex` output.
#'
#' Most packages ship with a full TeX Live installation, but **tabularray** is
#' often missing from minimal distributions like tinytex. Use
#' [fr_install_latex_deps()] to install everything at once.
#'
#' @return A character vector of CTAN package names.
#'
#' @seealso [fr_install_latex_deps()] to install these packages,
#'   [fr_render()] for PDF output.
#'
#' @examples
#' fr_latex_deps()
#'
#' @export
fr_latex_deps <- function() {
  fr_env$required_latex_pkgs
}


#' Install Required LaTeX Packages
#'
#' Proactively installs all LaTeX packages needed by arframe's PDF backend.
#' Checks which packages are missing via `kpsewhich`, then installs them.
#'
#' The installation strategy uses a two-step approach:
#' 1. Try [tinytex::tlmgr_install()] with a timeout (default 10 seconds).
#' 2. If tinytex times out or fails (common on corporate networks where
#'    `tlmgr` is restricted), fall back to the system `tlmgr` with an
#'    explicit CTAN mirror repository URL.
#'
#' @param timeout Integer. Maximum seconds to wait for
#'   [tinytex::tlmgr_install()] before falling back to system `tlmgr`.
#'   Default `10L`.
#' @param repository Character. CTAN mirror URL for the system `tlmgr`
#'   fallback. Default `"https://mirror.ctan.org/systems/texlive/tlnet"`.
#'   Change this if your network requires a specific mirror.
#'
#' @return Invisible `NULL`. Called for its side effect of installing packages.
#'
#' @seealso [fr_latex_deps()] for the package list,
#'   [fr_render()] for PDF output.
#'
#' @examples
#' \dontrun{
#' # Standard usage (tries tinytex first, falls back to system tlmgr)
#' fr_install_latex_deps()
#'
#' # Corporate network with specific mirror
#' fr_install_latex_deps(
#'   repository = "https://ctan.mirror.garr.it/mirrors/ctan/systems/texlive/tlnet"
#' )
#'
#' # Skip tinytex entirely (go straight to system tlmgr)
#' fr_install_latex_deps(timeout = 0L)
#' }
#'
#' @export
fr_install_latex_deps <- function(
  timeout = 10L,
  repository = "https://mirror.ctan.org/systems/texlive/tlnet"
) {
  pkgs <- fr_env$required_latex_pkgs
  missing <- find_missing_latex_pkgs(pkgs)

  if (length(missing) == 0L) {
    cli_inform(c("v" = "All required LaTeX packages are already installed."))
    return(invisible(NULL))
  }

  cli_inform(c("i" = "Missing LaTeX package{?s}: {.val {missing}}."))

  # Try tinytex::tlmgr_install first (with timeout via background process)
  if (requireNamespace("tinytex", quietly = TRUE) && timeout > 0L) {
    cli_inform(c("i" = "Trying {.fn tinytex::tlmgr_install} (timeout: {timeout}s)..."))
    success <- try_tinytex_install(missing, timeout)
    if (success) {
      still_missing <- find_missing_latex_pkgs(missing)
      if (length(still_missing) == 0L) {
        cli_inform(c("v" = "All packages installed via tinytex."))
        return(invisible(NULL))
      }
      missing <- still_missing
    }
    cli_inform(c(
      "!" = "tinytex::tlmgr_install timed out or failed.",
      "i" = "Falling back to system {.code tlmgr}."
    ))
  }

  # Fallback: system tlmgr with explicit repository
  sys_tlmgr <- Sys.which("tlmgr")
  if (!nzchar(sys_tlmgr)) {
    cli_abort(c(
      "Cannot install LaTeX packages: no {.code tlmgr} found.",
      "i" = "Install the missing packages manually:",
      " " = "{.code tlmgr --repository {repository} install {paste(missing, collapse = ' ')}}"
    ), call = caller_env())
  }

  cli_inform(c("i" = "Installing via system tlmgr: {.val {missing}}."))
  result <- system2(
    sys_tlmgr,
    c("--repository", repository, "install", missing),
    stdout = TRUE,
    stderr = TRUE
  )
  exit_code <- attr(result, "status") %||% 0L

  if (exit_code != 0L) {
    cli_abort(c(
      "System {.code tlmgr install} failed (exit code {exit_code}).",
      "i" = "Output: {paste(utils::tail(result, 5), collapse = '\\n')}",
      "i" = "Try manually: {.code tlmgr --repository {repository} install {paste(missing, collapse = ' ')}}"
    ), call = caller_env())
  }

  still_missing <- find_missing_latex_pkgs(missing)
  if (length(still_missing) > 0L) {
    cli::cli_warn(c(
      "!" = "Still missing after install: {.val {still_missing}}.",
      "i" = "Try installing manually or check your TeX Live setup."
    ))
  } else {
    cli_inform(c("v" = "All packages installed via system tlmgr."))
  }

  invisible(NULL)
}


#' Try tinytex::tlmgr_install with a timeout via a subprocess
#'
#' Runs the install in a background R process and waits up to `timeout`
#' seconds. Returns TRUE on success, FALSE on timeout or error.
#' @noRd
try_tinytex_install <- function(pkgs, timeout) {
  # Build a one-liner R script to run in a subprocess
  pkg_str <- paste0("'", pkgs, "'", collapse = ", ")
  script <- sprintf("tinytex::tlmgr_install(c(%s))", pkg_str)
  rscript <- file.path(R.home("bin"), "Rscript")

  tf <- tempfile(fileext = ".R")
  writeLines(script, tf)
  on.exit(unlink(tf), add = TRUE)

  # Run with timeout — system2 doesn't support timeout directly,
  # so use the system timeout command on Unix
  if (.Platform$OS.type == "unix") {
    exit <- tryCatch(
      system2("timeout", c(timeout, rscript, "--vanilla", tf),
              stdout = FALSE, stderr = FALSE),
      error = function(e) 1L
    )
  } else {
    # Windows: no system timeout, run directly and hope it completes
    exit <- tryCatch(
      system2(rscript, c("--vanilla", tf),
              stdout = FALSE, stderr = FALSE, timeout = timeout),
      error = function(e) 1L
    )
  }

  identical(exit, 0L)
}


#' Find missing LaTeX packages by checking for their .sty files
#' @noRd
find_missing_latex_pkgs <- function(pkgs) {
  kpsewhich <- Sys.which("kpsewhich")
  if (!nzchar(kpsewhich)) return(pkgs)

  missing <- character(0)
  for (pkg in pkgs) {
    sty <- paste0(pkg, ".sty")
    found <- tryCatch(
      system2(kpsewhich, sty, stdout = TRUE, stderr = TRUE),
      error = function(e) ""
    )
    if (length(found) == 0L || !nzchar(found[1L])) {
      missing <- c(missing, pkg)
    }
  }
  missing
}


# ── Internal compilation ─────────────────────────────────────────────────────

#' Render an fr_spec to PDF via XeLaTeX
#'
#' @param spec Finalized fr_spec object.
#' @param page_groups List of page group lists (data + group_label).
#' @param col_panels List of column name vectors (one per panel).
#' @param path Output file path (.pdf).
#' @noRd
render_pdf <- function(spec, page_groups, col_panels, path) {
  # 1. Write .tex to tempdir
  base_name <- file_path_sans_ext(basename(path))
  tex_dir <- tempdir()
  tex_path <- file.path(tex_dir, paste0(base_name, ".tex"))
  render_latex(spec, page_groups, col_panels, tex_path)

  # 2. Compile via shared helper
  compile_xelatex_doc(tex_path)

  # 3. Copy PDF to output path (skip if already in place)
  pdf_temp <- file.path(tex_dir, paste0(base_name, ".pdf"))
  if (
    normalizePath(pdf_temp, mustWork = FALSE) !=
      normalizePath(path, mustWork = FALSE)
  ) {
    file.copy(pdf_temp, path, overwrite = TRUE)
  }

  # 4. Cleanup temp files
  cleanup_latex_temps(tex_dir, base_name)

  invisible(path)
}


#' Compile a .tex file to PDF using XeLaTeX
#'
#' Shared compilation logic used by both `render_pdf()` (tables) and
#' `render_figure_pdf()` (figures). When tinytex is available, uses
#' `tinytex::xelatex()` which handles two-pass compilation AND auto-installs
#' missing LaTeX packages. Falls back to raw `system2()` with `find_xelatex()`
#' otherwise.
#'
#' @param tex_path Path to the .tex source file.
#' @return Invisible path to the compiled PDF.
#' @noRd
compile_xelatex_doc <- function(tex_path) {
  tex_dir <- dirname(tex_path)
  base_name <- file_path_sans_ext(basename(tex_path))

  # Set OSFONTDIR so XeLaTeX discovers fonts in ARFRAME_FONT_DIR

  font_dir <- get_font_dir()
  if (!is.null(font_dir)) {
    old_osfontdir <- Sys.getenv("OSFONTDIR", unset = NA)
    existing <- if (!is.na(old_osfontdir)) old_osfontdir else ""
    sep <- if (.Platform$OS.type == "windows") ";" else ":"
    new_val <- if (nzchar(existing)) {
      paste0(font_dir, sep, existing)
    } else {
      font_dir
    }
    Sys.setenv(OSFONTDIR = new_val)
    on.exit(
      {
        if (is.na(old_osfontdir)) {
          Sys.unsetenv("OSFONTDIR")
        } else {
          Sys.setenv(OSFONTDIR = old_osfontdir)
        }
      },
      add = TRUE
    )
  }

  if (requireNamespace("tinytex", quietly = TRUE)) {
    # tinytex::xelatex() handles two-pass compilation and auto-installs
    # missing packages via parse_install().
    # Set working directory to tempdir to prevent .log file leakage into
    # the user's working directory when tinytex retains logs on warnings.
    old_wd <- setwd(tex_dir)
    on.exit(setwd(old_wd), add = TRUE)
    tryCatch(
      tinytex::xelatex(tex_path),
      error = function(e) {
        log_file <- file.path(tex_dir, paste0(base_name, ".log"))
        report_latex_failure(log_file, tex_path, conditionMessage(e))
      }
    )
  } else {
    # Fallback: raw system2()
    xelatex <- find_xelatex()
    if (is.null(xelatex)) {
      cli_abort(c(
        "XeLaTeX not found on your system.",
        "i" = "Install {.pkg tinytex} for automatic LaTeX package management:",
        " " = "{.code install.packages(\"tinytex\")}",
        " " = "{.code tinytex::install_tinytex()}",
        " " = "{.code arframe::fr_install_latex_deps()}"
      ), call = caller_env())
    }

    args <- c(
      "-interaction=nonstopmode",
      "-output-directory",
      tex_dir,
      tex_path
    )
    system2(xelatex, args, stdout = TRUE, stderr = TRUE)
    system2(xelatex, args, stdout = TRUE, stderr = TRUE)

    # Check compilation succeeded
    pdf_path <- file.path(tex_dir, paste0(base_name, ".pdf"))
    if (!file.exists(pdf_path)) {
      log_file <- file.path(tex_dir, paste0(base_name, ".log"))
      report_latex_failure(log_file, tex_path)
    }
  }

  # Clean up auxiliary files (.log, .aux, .out, .fls, .fdb_latexmk)
  # tinytex::xelatex(clean = TRUE) handles this for the tinytex path;
  # this covers the system2 fallback and any leftover files.
  aux_exts <- c(".log", ".aux", ".out", ".fls", ".fdb_latexmk")
  aux_files <- file.path(tex_dir, paste0(base_name, aux_exts))
  unlink(aux_files[file.exists(aux_files)])

  invisible(file.path(tex_dir, paste0(base_name, ".pdf")))
}


#' Report LaTeX compilation failure with actionable diagnostics
#'
#' Parses the XeLaTeX log file for missing `.sty` files and produces a
#' targeted error message. For missing packages, suggests
#' `fr_install_latex_deps()`. For other errors, shows the log tail.
#'
#' @param log_file Path to the .log file.
#' @param tex_path Path to the .tex source (shown in error message).
#' @param original_msg Optional error message from tinytex (prepended).
#' @return Does not return; always aborts via [cli::cli_abort()].
#' @noRd
report_latex_failure <- function(
  log_file,
  tex_path,
  original_msg = NULL,
  call = caller_env()
) {
  if (!file.exists(log_file)) {
    cli_abort(
      c(
        original_msg %||% "XeLaTeX compilation failed.",
        "i" = "Source file: {.path {tex_path}}",
        "i" = "No log file found for diagnostics."
      ),
      call = call
    )
  }

  log_lines <- readLines(log_file, warn = FALSE)

  # Detect missing .sty files
  sty_pattern <- "! LaTeX Error: File `([^']+)\\.sty' not found"
  sty_matches <- regmatches(log_lines, regexec(sty_pattern, log_lines))
  missing_pkgs <- vapply(
    sty_matches,
    function(m) {
      if (length(m) >= 2L) m[[2L]] else NA_character_
    },
    character(1)
  )
  missing_pkgs <- unique(missing_pkgs[!is.na(missing_pkgs)])

  if (length(missing_pkgs) > 0L) {
    pkg_list <- paste0("{.pkg ", missing_pkgs, "}", collapse = ", ")
    cli_abort(
      c(
        original_msg %||%
          "XeLaTeX compilation failed due to missing LaTeX packages.",
        "x" = paste0("Missing: ", pkg_list),
        "i" = "Install with: {.code arframe::fr_install_latex_deps()}",
        "i" = "Or manually: {.code tinytex::tlmgr_install({deparse(missing_pkgs)})}"
      ),
      call = call
    )
  }

  # Generic failure: show log tail
  log_tail <- utils::tail(log_lines, 20L)
  safe_log <- gsub(
    "{",
    "{{",
    fixed = TRUE,
    gsub("}", "}}", log_tail, fixed = TRUE)
  )
  cli_abort(
    c(
      original_msg %||% "XeLaTeX compilation failed.",
      "i" = "Source file: {.path {tex_path}}",
      "i" = "Last 20 lines of log:",
      paste0("  ", safe_log)
    ),
    call = call
  )
}


#' Clean up LaTeX temporary files
#'
#' @param tex_dir Directory containing temp files.
#' @param base_name File base name (no extension).
#' @noRd
cleanup_latex_temps <- function(tex_dir, base_name) {
  exts <- c(".aux", ".log", ".out", ".toc")
  for (ext in exts) {
    unlink(file.path(tex_dir, paste0(base_name, ext)))
  }
}


#' Find xelatex binary
#'
#' Checks: (1) Sys.which, (2) tinytex if available.
#'
#' @return Path to xelatex binary, or NULL if not found.
#' @noRd
find_xelatex <- function() {
  # 1. System PATH
  path <- Sys.which("xelatex")
  if (nzchar(path)) {
    return(unname(path))
  }

  # 2. tinytex
  if (requireNamespace("tinytex", quietly = TRUE)) {
    path <- tryCatch(
      tinytex::tinytex_root(),
      error = function(e) NULL
    )
    if (!is.null(path)) {
      bin <- file.path(path, "bin", "*", "xelatex")
      candidates <- Sys.glob(bin)
      if (length(candidates) > 0L) {
        return(candidates[1L])
      }

      # Windows: .exe
      bin_exe <- file.path(path, "bin", "*", "xelatex.exe")
      candidates <- Sys.glob(bin_exe)
      if (length(candidates) > 0L) return(candidates[1L])
    }
  }

  NULL
}
